### PR TITLE
Create slider component using radio buttons

### PR DESCRIPTION
**Pull request by jongmin141215**
Before, I used ion-range to create a slider, but I wasn't sure how to reset the selected value.
So I created another slider using radio buttons so that I can reset the form. 

We should choose which slider we're going to use. 

screen shot 2017-08-01 at 8 55 13 pm

This is not as pretty but it can be more customizable I think.

### CODE REVIEW

**Comment by phortonssf** [comment]
I might of preferred the other slider but it is not a big deal to me. Which do you prefer?

**Comment by jongmin141215** [comment]
The reason I created this is I don't know how to reset the selected value from the ion-range slider. 
If we can figure that out, ion-range would be good. Otherwise radio-button slider can be an option.

**Comment by jongmin141215** [comment]
Currently I'm just changing 'question text' when user clicks on the next question button. I guess if I load the whole page again when user clicks on the next question button, the value may be reset. I may try that tomorrow.

**Comment by phortonssf** [comment]
I believe that would reload the slider correct

**Comment by jongmin141215** [comment]
Yeah I'll try that.

**Comment by phortonssf** [comment]
Yeah it should work when we are actually leaving the page. I left the page and return to it and value is reset.

**Pull request closed without merging**
